name: eazy_client_mvp
description: Eazy Food & Flower Delivery Client MVP (Flutter)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  go_router: ^14.0.0
  http: ^1.2.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.7.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  google_maps_flutter: ^2.5.3
  google_places_flutter: ^2.1.1
  flutter_stripe: ^10.0.0
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  collection: ^1.18.0
  crypto: ^3.0.3
  google_fonts: ^6.1.0
  json_annotation: ^4.9.0
  flutter_rating_bar: ^4.0.1
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  json_serializable: ^6.8.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png
  generate: true
